services:
  gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    depends_on:
      - gateway-db
    restart: unless-stopped
    ports:
      - 3000:3000
      - 3002:3002
    environment:
      PORT: 3000
      DB_HOST: gateway-db
      DB_PORT: 5432
      DB_USER: gateway
      DB_PW: gateway
      DB_DB: gateway
      WS_PORT: 3001
      WS_PROXY_PORT: 3002
  gateway-db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: gateway
      POSTGRES_PASSWORD: gateway
      POSTGRES_DB: gateway

  auth-service:
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
    depends_on:
      - auth-db
      - gateway
    restart: unless-stopped
    ports:
      - 3010:3010
    environment:
      PG_HOST: auth-db
      PG_PORT: 5432
      PG_USER: auth
      PG_PW: auth
      PG_DB: auth
      GATEWAY_HOST: gateway
      GATEWAY_PORT: 3000
      PORT: 3010

  auth-db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
      POSTGRES_DB: auth

# TODO setup volume for db