include:
  - compose.base.yaml

services:
  game-service:
    build:
      context: .
      dockerfile: ./apps/game-service/Dockerfile
    depends_on:
      - gateway
      - game-db
    environment:
      DB_HOST: game-db
      DB_PORT: 5432
      DB_USER: game
      DB_PW: game
      DB_DB: game
      GATEWAY_HOST: gateway
      GATEWAY_PORT: 3000
      PORT: 4030
      SERVICE_KEY: game-service
    ports:
      - 4030:4030
  
  game-db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: game
      POSTGRES_PASSWORD: game
      POSTGRES_DB: game

  ttt-db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ttt
      POSTGRES_PASSWORD: ttt
      POSTGRES_DB: ttt

  ttt-service:
    build: 
      context: .
      dockerfile: ./apps/ttt-service/Dockerfile
    depends_on:
      - auth-service
      - ttt-db
      - gateway
    environment:
      DB_HOST: ttt-db
      DB_PORT: 5432
      DB_USER: ttt
      DB_PW: ttt
      DB_DB: ttt
      GATEWAY_HOST: gateway
      GATEWAY_PORT: 3000
      SERVICE_KEY: ttt-service
      PORT: 4031
      WS_SERVICE_KEY: ttt-ws-service
      WS_PORT: 8031

  c4-db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: c4
      POSTGRES_PASSWORD: c4
      POSTGRES_DB: c4

  c4-service:
    build: 
      context: .
      dockerfile: ./apps/c4-service/Dockerfile
    depends_on:
      - auth-service
      - c4-db
      - gateway
    environment:
      DB_HOST: c4-db
      DB_PORT: 5432
      DB_USER: c4
      DB_PW: c4
      DB_DB: c4
      GATEWAY_HOST: gateway
      GATEWAY_PORT: 3000
      SERVICE_KEY: c4-service
      PORT: 4032
      WS_SERVICE_KEY: c4-ws-service
      WS_PORT: 8032