name: CI
on:
  push:
    branches:
      # Change this if your primary branch is not main
      - dev/9-autotesting
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello GitHub Actions!"